markdown: kramdown
baseurl: /citysdk-ld
exclude: ['Capfile', 'config', 'REVISION', 'README.md']

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default

prose:
  ignore:
    - .gitignore
    - /\..*
    - /_config.yml
    - /LICENSE.md
    - /README.md
    - /js
    - /css
    - /layouts
